(function(){
"use strict";
const $=id=>document.getElementById(id);
const lobby=$("coopLobby"),createBtn=$("coopCreate"),joinBtn=$("coopJoin"),closeBtn=$("coopClose"),signal=$("coopSignal"),output=$("coopCodeOut"),input=$("coopCodeIn"),copyBtn=$("coopCopy"),nextBtn=$("coopNext"),startBtn=$("coopHostStart"),status=$("coopStatus"),normalStart=$("startButton");
const view=document.createElement("div");view.id="coopGuestView";view.innerHTML='<div id="coopGuestBar"><span id="coopGuestInfo">🐱🐱 Conectando…</span><button id="coopGuestLeave" type="button">Salir del cooperativo</button></div><video id="coopGuestVideo" autoplay playsinline muted></video><div id="coopGuestPhase">Esperando al anfitrión…</div>';document.body.appendChild(view);
const video=$("coopGuestVideo"),guestInfo=$("coopGuestInfo"),guestPhase=$("coopGuestPhase");
let pc=null,channel=null,mode="none",phase="",phaseAt=0,controlAt=0,lastMouseSend=0,copyState="",media=null,connected=false,coopStarted=false;
const remote={x:0,y:0,angle:0,shootAnim:0,hurtAnim:0,r:22,lastShot:-Infinity,lastManual:-Infinity,manualCount:0,lastBloquito:-Infinity,keys:{},aimX:0,aimY:0,clicks:0,receivedAt:0};
const guestKeys={};let guestAimX=.5,guestAimY=.5,guestClicks=0;
function msg(s){status.textContent=s}
function enabled(){return mode!=="none"}
function send(x){if(channel?.readyState==="open")try{channel.send(JSON.stringify(x))}catch(e){}}
function allowStart(flag){normalStart.hidden=flag;normalStart.disabled=flag}
function resetRemote(){remote.x=Math.min(canvas.width-40,player.x+85);remote.y=Math.min(canvas.height-40,player.y+35);remote.angle=0;remote.shootAnim=0;remote.hurtAnim=0;remote.lastShot=-Infinity;remote.lastManual=-Infinity;remote.manualCount=0;remote.lastBloquito=-Infinity;remote.keys={};remote.aimX=remote.x+90;remote.aimY=remote.y;remote.clicks=0}
function release(){if(channel){try{channel.close()}catch(e){}}channel=null;if(pc){try{pc.close()}catch(e){}}pc=null;if(media){for(const t of media.getTracks())t.stop()}media=null;connected=false;mode="none";phase="";closeBtn.hidden=true;createBtn.disabled=false;joinBtn.disabled=false;signal.hidden=true;startBtn.hidden=true;nextBtn.hidden=true;output.value="";input.value="";view.style.display="none";video.srcObject=null;allowStart(false);msg("Conexión cerrada. Puedes crear otra partida.")}
function connectionDropped(){if(!connected)return;connected=false;remote.keys={};remote.clicks=0;if(mode==="host"){msg("El invitado se ha desconectado. La partida ya no recibe sus controles; cancela y crea una sala nueva si quieres reconectar.");}else if(mode==="guest"){guestPhase.textContent="Se perdió la conexión. Pulsa Salir para volver al menú.";guestInfo.textContent="🔌 Desconectado"}}
function bindChannel(ch){channel=ch;channel.onopen=()=>{connected=true;if(mode==="host"){nextBtn.hidden=true;signal.hidden=true;startBtn.hidden=false;msg("¡Conectados! Pulsa Empezar partida cooperativa. Solo el anfitrión elige mejoras y fusiones.")}else{startPanel.style.display="none";view.style.display="flex";guestPhase.textContent="¡Conectados! Esperando al anfitrión…";msg("Conectado al anfitrión.")}};channel.onclose=connectionDropped;channel.onerror=()=>msg("Error en la conexión WebRTC.");channel.onmessage=e=>{let d;try{d=JSON.parse(e.data)}catch(err){return}if(mode==="host"&&d.t==="i"){remote.keys=d.k&&typeof d.k==="object"?d.k:{};remote.aimX=Math.max(0,Math.min(canvas.width,Number(d.x)*canvas.width||0));remote.aimY=Math.max(0,Math.min(canvas.height,Number(d.y)*canvas.height||0));remote.clicks=Math.min(2,remote.clicks+(d.c?1:0));remote.receivedAt=performance.now()}else if(mode==="guest"&&d.t==="s"){guestInfo.textContent=`🐱🐱 Ronda ${d.w} · Nv.${d.l} · Vida ${d.hp} · ${d.pts} gatitos`;guestPhase.textContent=d.p}}}
function makePC(){if(!window.RTCPeerConnection)throw Error("Este navegador no es compatible con WebRTC.");pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});pc.onconnectionstatechange=()=>{const st=pc?.connectionState;if(st==="failed"||st==="disconnected"||st==="closed")connectionDropped()};pc.onicecandidateerror=e=>{if(e.errorCode!==701)console.warn("Coop ICE",e.errorCode)};return pc}
function gather(p){return new Promise(resolve=>{if(p.iceGatheringState==="complete")return resolve();let settled=false;const finish=()=>{if(settled)return;settled=true;p.removeEventListener("icegatheringstatechange",changed);resolve()};function changed(){if(p.iceGatheringState==="complete")finish()}p.addEventListener("icegatheringstatechange",changed);setTimeout(finish,12000)})}
function pack(desc){return btoa(JSON.stringify({t:desc.type,s:desc.sdp,v:1}))}
function unpack(value,expected){const data=JSON.parse(atob(String(value).replace(/\s/g,"")));if(data?.t!==expected||typeof data.s!=="string"||data.s.length>180000)throw Error("El código no es una "+expected+" válida.");return {type:data.t,sdp:data.s}}
async function host(){release();mode="host";closeBtn.hidden=false;createBtn.disabled=true;joinBtn.disabled=true;signal.hidden=false;allowStart(true);output.value="";input.value="";$("coopCodeLabel").textContent="1. Envía este código de invitación al otro jugador";$("coopInputLabel").textContent="3. Pega aquí la respuesta del invitado";nextBtn.textContent="Conectar con la respuesta";nextBtn.hidden=true;msg("Creando conexión…");try{makePC();media=canvas.captureStream(15);for(const track of media.getTracks())pc.addTrack(track,media);bindChannel(pc.createDataChannel("gatitos-coop",{ordered:false,maxRetransmits:2}));const offer=await pc.createOffer();await pc.setLocalDescription(offer);await gather(pc);if(mode!=="host")return;output.value=pack(pc.localDescription);nextBtn.hidden=false;msg("1. Copia tu código y envíaselo al invitado.\n2. El invitado genera una respuesta y te la envía.\n3. Pégala aquí y pulsa Conectar.")}catch(e){msg("No se pudo crear la partida: "+e.message);console.error(e);release()}}
async function join(){release();mode="guest";closeBtn.hidden=false;signal.hidden=false;allowStart(true);$("coopCodeLabel").textContent="2. Envía esta respuesta al anfitrión";$("coopInputLabel").textContent="1. Pega el código recibido del anfitrión";output.value="";input.value="";nextBtn.textContent="Generar respuesta";nextBtn.hidden=false;msg("Pega el código de invitación y pulsa Generar respuesta.")}
async function next(){nextBtn.disabled=true;try{if(mode==="host"){await pc.setRemoteDescription(unpack(input.value,"answer"));nextBtn.hidden=true;msg("Respuesta aplicada. Esperando a que WebRTC establezca la conexión…") }else if(mode==="guest"){if(pc){try{pc.close()}catch(e){}}makePC();pc.ontrack=e=>{video.srcObject=e.streams[0]||new MediaStream([e.track]);video.play().catch(()=>{});};pc.ondatachannel=e=>bindChannel(e.channel);await pc.setRemoteDescription(unpack(input.value,"offer"));const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await gather(pc);if(mode!=="guest")return;output.value=pack(pc.localDescription);nextBtn.hidden=true;msg("Copia la respuesta y envíasela al anfitrión. Esperando a que termine la conexión…")}}catch(e){msg("No se pudo completar el intercambio: "+e.message);console.error(e)}finally{nextBtn.disabled=false}}
function autoFish(manual=false){if(!connected||!gameStarted||gameOver||paused||choosingUpgrade)return;const now=gameNow(),interval=manual?100:getShotInterval();if(now-(manual?remote.lastManual:remote.lastShot)<interval)return;if(manual&&remote.manualCount>=100)return;if(manual){remote.lastManual=now;remote.manualCount++}else remote.lastShot=now;const angle=Math.atan2(remote.aimY-remote.y,remote.aimX-remote.x);const crit=Math.random()<getCurrentCritChance(),boom=Math.random()<upgrades.boomerangChance,scale=upgrades.fishSize*(manual?1.3:1);const speed=610*upgrades.fishSpeed;fishes.push({x:remote.x+Math.cos(angle)*54,y:remote.y+Math.sin(angle)*54,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,angle,damage:upgrades.damage*getZoomiesDamageMultiplier()*(manual?1.3:0.75)*(crit?getCriticalDamageMultiplier():1),life:boom?3.35:1.45,scale,pierce:Math.random()<upgrades.pierceChance,boomerang:boom,crit,returning:false,age:0,turnTime:boom?.95:0,hitIds:new Set()});remote.shootAnim=.12;shots++;if(runStats)runStats.shotsFired++}
function update(dt){if(mode!=="host"||!connected||!gameStarted||gameOver||paused||choosingUpgrade)return;if(performance.now()-remote.receivedAt>1300){remote.keys={};remote.clicks=0}let mx=0,my=0;const k=remote.keys;if(k.w||k.arrowup)my--;if(k.s||k.arrowdown)my++;if(k.a||k.arrowleft)mx--;if(k.d||k.arrowright)mx++;const length=Math.hypot(mx,my);if(length){const speed=player.speed*upgrades.moveSpeed*getZoomiesMoveMultiplier()*getStarSpeedMultiplier()*dt;remote.x=Math.max(remote.r,Math.min(canvas.width-remote.r,remote.x+mx/length*speed));remote.y=Math.max(remote.r,Math.min(canvas.height-remote.r,remote.y+my/length*speed))}remote.angle=Math.atan2(remote.aimY-remote.y,remote.aimX-remote.x);remote.shootAnim=Math.max(0,remote.shootAnim-dt);remote.hurtAnim=Math.max(0,remote.hurtAnim-dt);autoFish();if(remote.clicks){remote.clicks=0;autoFish(true)}for(const cat of cats){if(!isCombatTargetAvailable(cat)||cat.damageCooldown>0)continue;if(Math.hypot(cat.x-remote.x,cat.y-remote.y)<cat.r+remote.r-4){cat.damageCooldown=.75;remote.hurtAnim=.23;takePlayerDamage(Math.max(1,cat.small?2:5),"El segundo gatito recibió daño 🐱",.2);break}}}
function draw(){if(mode!=="host"||!connected||!gameStarted)return;ctx.save();drawEntityShadow(remote.x,remote.y,24,9,.20);ctx.translate(remote.x,remote.y);ctx.rotate(remote.angle);ctx.fillStyle=remote.hurtAnim>0?"#ff80a5":"#f5b8e7";ctx.strokeStyle="#7950a1";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-18,-11);ctx.lineTo(-14,-35);ctx.lineTo(-3,-24);ctx.lineTo(12,-35);ctx.lineTo(18,-10);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(0,0,remote.r,0,2*Math.PI);ctx.fill();ctx.stroke();ctx.fillStyle="#49304f";for(const x of [-9,9]){ctx.beginPath();ctx.arc(x,-2,3,0,2*Math.PI);ctx.fill()}ctx.beginPath();ctx.moveTo(-5,8);ctx.lineTo(0,12);ctx.lineTo(5,8);ctx.stroke();ctx.fillStyle="#ff8fab";ctx.fillRect(19,-4,remote.shootAnim>0?23:15,8);ctx.restore();ctx.save();ctx.textAlign="center";ctx.font="bold 12px Arial";ctx.lineWidth=3;ctx.strokeStyle="#281735";ctx.strokeText("J2",remote.x,remote.y-remote.r-11);ctx.fillStyle="#fff";ctx.fillText("J2",remote.x,remote.y-remote.r-11);ctx.restore()}
function sync(){if(mode!=="host"||!connected||performance.now()-phaseAt<280)return;phaseAt=performance.now();let p="¡A jugar!";if(!gameStarted)p="Esperando al anfitrión…";else if(gameOver)p="Fin de la partida. El anfitrión controla el menú.";else if(choosingUpgrade||levelUpPanel.style.display==="flex")p="El anfitrión está eligiendo mejoras o fusiones.";else if(paused||pausePanel.style.display==="flex")p="Partida en pausa: esperando al anfitrión.";else if(victoryPanel.style.display==="flex")p="¡Victoria! El anfitrión elige si continuar.";else if(shopAvailable)p="Tienda: el anfitrión realiza las compras.";send({t:"s",w:wave||1,l:level||1,hp:Math.max(0,Math.ceil(life||0)),pts:score||0,p})}
function sendGuest(c=0){if(mode!=="guest"||!connected)return;send({t:"i",k:guestKeys,x:guestAimX,y:guestAimY,c})}
function guestPointer(e){const rect=video.getBoundingClientRect();const naturalW=video.videoWidth||canvas.width,naturalH=video.videoHeight||canvas.height,ratio=Math.min(rect.width/naturalW,rect.height/naturalH),w=naturalW*ratio,h=naturalH*ratio;guestAimX=Math.min(1,Math.max(0,(e.clientX-rect.left-(rect.width-w)/2)/w));guestAimY=Math.min(1,Math.max(0,(e.clientY-rect.top-(rect.height-h)/2)/h));if(performance.now()-lastMouseSend>25){lastMouseSend=performance.now();sendGuest()}}
createBtn.addEventListener("click",host);joinBtn.addEventListener("click",join);closeBtn.addEventListener("click",()=>{release();createBtn.disabled=false;joinBtn.disabled=false});nextBtn.addEventListener("click",next);copyBtn.addEventListener("click",async()=>{if(!output.value)return;try{await navigator.clipboard.writeText(output.value);msg("Código copiado. Envíalo por un mensaje privado.")}catch(e){output.focus();output.select();msg("Selecciona el código y pulsa Ctrl+C para copiarlo.")}});startBtn.addEventListener("click",()=>{if(mode!=="host"||!connected)return;startBtn.hidden=true;coopStarted=true;startGame();msg("Partida cooperativa activa: ranking y récords desactivados.")});$("coopGuestLeave").addEventListener("click",()=>{release();createBtn.disabled=false;joinBtn.disabled=false;startPanel.style.display="flex"});video.addEventListener("mousemove",guestPointer);video.addEventListener("mousedown",e=>{if(mode!=="guest")return;e.preventDefault();guestPointer(e);if(e.button===0)sendGuest(1)});video.addEventListener("contextmenu",e=>e.preventDefault());
window.addEventListener("keydown",e=>{if(mode!=="guest"||!connected||view.style.display!=="flex")return;const k=e.key.toLowerCase();if(["w","a","s","d","arrowup","arrowdown","arrowleft","arrowright"," "].includes(k)){e.preventDefault();e.stopImmediatePropagation();guestKeys[k]=true;sendGuest()}},true);window.addEventListener("keyup",e=>{if(mode!=="guest"||!connected)return;const k=e.key.toLowerCase();if(guestKeys[k]){delete guestKeys[k];sendGuest()}},true);window.addEventListener("blur",()=>{for(const k in guestKeys)delete guestKeys[k];sendGuest()});setInterval(()=>{if(mode==="guest"&&connected)sendGuest()},90);
window.coopTest={get hostActive(){return mode==="host"&&connected},get inRun(){return coopStarted},resetSolo(){coopStarted=false},resetPlayer:resetRemote,update,draw,sync};
})();
