const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),http=require('http');
const results=[],errors=[];
(async()=>{
 const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;const file=path.join(__dirname,'..',pathname==='/'?'index.html':pathname);try{res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.mp3':'audio/mpeg','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch(e){res.statusCode=404;res.end()}});
 await new Promise(resolve=>server.listen(8765,'127.0.0.1',resolve));
 const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE||chromium.executablePath(),args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],headless:true});
 const context=await browser.newContext({viewport:{width:1366,height:768}});
 await context.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:8765/')?r.continue():r.abort());
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.stack));page.on('dialog',d=>d.accept());
 async function test(name,body){try{await body();results.push({name,passed:true});console.log('PASS',name)}catch(e){results.push({name,passed:false,error:e.stack});console.log('FAIL',name,e.message)}}
 async function clickCard(text){await page.waitForTimeout(850);const loc=text?page.locator('#upgradeCards button.upgradeCard').filter({hasText:text}):page.locator('#upgradeCards button.upgradeCard:not(:disabled)').first();await loc.click();}
 await page.goto('http://127.0.0.1:8765/');await page.waitForFunction(()=>typeof startGame==='function');
 await test('Initial menu and no-name validation',async()=>{assert.equal(await page.locator('#startPanel').isVisible(),true);await page.click('#startButton');assert.match(await page.locator('#nameWarning').textContent(),/nombre/);assert.equal(await page.evaluate(()=>gameStarted),false)});
 await test('All four menu dropdowns open with content and close others',async()=>{for(const id of ['achievementsPanel','cosmeticsPanel','howToPlay','patchNotesPanel']){await page.locator('#'+id+' summary').click();await page.waitForTimeout(100);assert.equal(await page.locator('#'+id).evaluate(n=>n.open),true);assert.equal(await page.locator('#startDropdownContentSlot').evaluate(n=>n.children.length>0),true)}await page.locator('#patchNotesPanel summary').click()});
 await test('Start and real audio playback',async()=>{await page.fill('#playerNameInput','Prueba local');await page.click('#startButton');await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>gameStarted),true);assert.equal(await page.evaluate(()=>bgMusic.paused),false);assert.ok(await page.evaluate(()=>bgMusic.currentTime)>0)});
 await test('Keyboard movement and mouse firing',async()=>{const x=await page.evaluate(()=>player.x);await page.keyboard.down('d');await page.waitForTimeout(250);await page.keyboard.up('d');assert.ok(await page.evaluate(()=>player.x)>x+25);const before=await page.evaluate(()=>shots);await page.mouse.click(950,400);assert.equal(await page.evaluate(()=>shots),before+1)});
 await test('Pause freezes simulation and resumes music',async()=>{await page.keyboard.press('Space');const before=await page.evaluate(()=>simulationMs);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>simulationMs),before);assert.equal(await page.evaluate(()=>bgMusic.paused),true);await page.click('#resumeButton');await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>paused),false);assert.equal(await page.evaluate(()=>bgMusic.paused),false)});
 await test('Right mouse selects target without firing',async()=>{await page.evaluate(()=>{restart();upgrades.holdShoot=true;spawnCat(900,400);cats[0].speed=0;spawnCooldown=999});const n=await page.evaluate(()=>shots);await page.mouse.move(900,400);await page.mouse.down({button:'right'});await page.waitForTimeout(300);await page.mouse.up({button:'right'});assert.equal(await page.evaluate(()=>shots),n);assert.equal(await page.evaluate(()=>selectedTarget!==null),true)});
 await test('Real card clicks preserve rainbow plus level reward',async()=>{await page.evaluate(()=>{restart();xp=xpNeed-1;spawnCat(100,100);cats[0].rainbow=true;killCat(0)});assert.match(await page.locator('#upgradeTitle').textContent(),/nivel/);await clickCard();assert.match(await page.locator('#upgradeTitle').textContent(),/arcoíris/);await clickCard();assert.equal(await page.evaluate(()=>choosingUpgrade),false);assert.equal(await page.evaluate(()=>Object.values(upgradeLevels).reduce((a,b)=>a+b,0)+uniqueFusionKeys.filter(k=>hasUniqueUpgrade(k)).length),2)});
 for(const type of ['giantCat','duck','seal','demon'])await test('Browser boss combat, reward and shop: '+type,async()=>{
   await page.evaluate(type=>{restart();wave=20;const choose=chooseNextBossType;chooseNextBossType=()=>type;spawnBoss();chooseNextBossType=choose;safeTeleportInvulnUntil=gameNow()+100000;spawnCooldown=999},type);
   await page.waitForFunction(()=>!bossMusic.paused,{},{timeout:5000});
   assert.equal(await page.evaluate(()=>bossMusic.paused),false);
   await page.evaluate(()=>damageBoss(boss.hp*100));await clickCard();assert.match(await page.locator('#upgradeTitle').textContent(),/Tienda/);
   await clickCard('Salir de la tienda');await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>bgMusic.paused),false);assert.equal(await page.evaluate(()=>boss===null),true);
 });
 await test('Purchase and real two-stage fusion UI',async()=>{await page.evaluate(()=>{restart();coins=100;upgradeLevels.damage=5;upgradeLevels.shield=5;applyUpgradeStatsFromLevels();openCoinShop()});await clickCard('Fusión de mejoras');await clickCard('Mimos potentes');await clickCard('Escudo de pececitos');assert.equal(await page.evaluate(()=>!!doneFusionPairs['damage+shield']),true);assert.equal(await page.evaluate(()=>coins),95);await clickCard('Salir de la tienda')});
 await test('Fourth boss reward then victory and continue',async()=>{await page.evaluate(()=>{restart();wave=20;defeatedBossTypes=new Set(['giantCat','duck','seal']);const choose=chooseNextBossType;chooseNextBossType=()=> 'demon';spawnBoss();chooseNextBossType=choose;damageBoss(boss.hp*100)});assert.equal(await page.locator('#victoryPanel').isVisible(),false);await clickCard();assert.equal(await page.locator('#victoryPanel').isVisible(),true);await page.click('#victoryContinue');assert.equal(await page.evaluate(()=>gameOver),false);assert.equal(await page.evaluate(()=>shopAvailable),true);await clickCard('Salir de la tienda')});
 await test('Death frame, game-over screen, restart and menu',async()=>{await page.evaluate(()=>{restart();life=1;quacks.push({x:player.x,y:player.y,vx:0,vy:0,r:10,life:4});tunaDrops.push({x:player.x,y:player.y,r:10,life:4,wobble:0});update(1/60)});assert.equal(await page.evaluate(()=>life),0);assert.equal(await page.locator('#gameOverPanel').isVisible(),true);await page.click('#gameOverRestart');assert.equal(await page.evaluate(()=>life),100);await page.keyboard.press('Space');await page.click('#menuButton');assert.equal(await page.evaluate(()=>gameStarted),false);assert.equal(await page.locator('#startPanel').isVisible(),true);assert.equal(await page.evaluate(()=>bgMusic.paused&&bossMusic.paused),true)});
 await test('Saved cosmetics, achievements, name and volume survive reload',async()=>{await page.evaluate(()=>{cosmeticScales=500;buyCosmetic('player_pink');setAchievementStatMax('cats',1234);saveAchievements();musicVolume=.4;saveMusicSettings()});await page.reload();await page.waitForFunction(()=>typeof startGame==='function');assert.equal(await page.evaluate(()=>selectedCosmetics.player),'player_pink');assert.equal(await page.evaluate(()=>cosmeticScales),400);assert.equal(await page.evaluate(()=>achievementValue('cats')),1234);assert.equal(await page.evaluate(()=>musicVolume),.4);assert.equal(await page.locator('#playerNameInput').inputValue(),'Prueba local')});
 await test('Menu remains usable at 800x600 and 1920x1080',async()=>{await page.evaluate(()=>returnToMainMenu());for(const [w,h] of [[800,600],[1920,1080]]){await page.setViewportSize({width:w,height:h});await page.locator('#startButton').scrollIntoViewIfNeeded();const box=await page.locator('#startButton').boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=w&&box.y+box.height<=h);await page.locator('#achievementsPanel summary').click();await page.waitForTimeout(100);await page.locator('#achievementsPanel summary').click();}await page.setViewportSize({width:1366,height:768})});
 await test('Corrupt storage is recoverable in real browser',async()=>{await page.evaluate(()=>{localStorage.setItem('gatitos_cosmetic_owned','{}');localStorage.setItem('gatitos_achievements_state_v1','null');localStorage.setItem('gatitos_music_volume','NaN')});await page.reload();await page.waitForFunction(()=>typeof startGame==='function');await page.fill('#playerNameInput','Prueba local');await page.click('#startButton');assert.equal(await page.evaluate(()=>gameStarted),true);assert.equal(await page.evaluate(()=>Number.isFinite(musicVolume)),true)});
 await test('Long accelerated simulation and mixed entity rendering',async()=>{
  const out=await page.evaluate(()=>{
   restart();let steps=0,choices=0;const before=performance.now();
   for(let frame=0;frame<18000;frame++){
    if(gameOver)break;
    if(choosingUpgrade){const menu=autoChoiceMenu;const c=menu.choices.find(c=>c.skipShop)||menu.choices.find(c=>!c.locked);menu.onPick(c);choices++;continue;}
    // Controlled invulnerability keeps the soak test running; it is not a balance/playthrough claim.
    safeTeleportInvulnUntil=gameNow()+1000;
    const target=boss||cats[0];if(target){mouse.x=target.x;mouse.y=target.y;shootFish();}
    if(boss&&frame%1200===0)damageBoss(boss.hp*100);
    update(1/60);cleanBrokenEntities();if(frame%60===0)render();steps++;
   }
   return {steps,choices,wave,seconds:simulationMs/1000,error:window.__lastGameError,elapsed:performance.now()-before,finite:Number.isFinite(life)&&Number.isFinite(player.x)};
  });assert.equal(out.error,undefined);assert.equal(out.finite,true);assert.ok(out.steps>10000);console.log('SOAK',JSON.stringify(out));
 });
 await test('No uncaught game errors',async()=>{assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>window.__lastGameError),undefined)});
 const browserVersion=browser.version();await browser.close();await new Promise(resolve=>server.close(resolve));
 fs.writeFileSync(path.join(__dirname,'browser-results.json'),JSON.stringify({browserVersion,results,errors},null,2));console.log(`${results.filter(r=>r.passed).length}/${results.length} passed`);if(results.some(r=>!r.passed))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
